# Generated by Django 6.0.5 on 2026-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('business_profile_count', models.IntegerField()),
                ('offer_count', models.IntegerField()),
            ],
        ),
    ]
